title: GIZ! AOT
email: gizipp.gizipp@gmail.com
description: >
  Bukan tempat baca manga attack on titan dan nonton online gratis. Hanya seru-seruan saja. :)
logo: "/android-chrome-192x192.png"

name: 'GIZ! AOT'
bio: >
  Mom
author_image: "/assets/images/author.jpg"
url: 'https://aot.gizipp.com' # the base hostname & protocol for your site
baseurl: "/amp" # the subpath of your site, e.g. /blog
permalink: /:title
paginate:	999 # The number of posts to show per page on your homepage

# Google Analytics
analytics_id:

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-toc

jekyll-minifier:
  uglifier_args:
    harmony: true

include:
  - '_pages'
  - '_redirects'

exclude:
  - LICENSE
  - README.md
  - ideas

amp: true
destination: _site/amp
